version: "3"
services:
  pg:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test
  redis:
    image: redis
    ports:
      - "6379:6379"