name: Docker Image CI

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      id: publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#        registry: ${{ secrets.REGISTRY }}
        tag_names: true
